services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://ben:portfolio2@db:3306/portfolio2.0"
    depends_on:
      - db

  db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: portfolio2
      MYSQL_DATABASE: portfolio2.0
      MYSQL_USER: ben
      MYSQL_PASSWORD: portfolio2  
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
